# Generated by Django 5.1.3 on 2025-01-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auto_Plate", "0002_alter_vehicle_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="parking_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Auto_Plate.parkinglot",
            ),
        ),
    ]
